# Estágio 1: Construir a aplicação React
FROM node:16.13 as build

# Crie e defina o diretório de trabalho
WORKDIR /app

# Copie os arquivos de dependências
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o código da aplicação
COPY . .

# Construa o projeto usando Vite
RUN npm run build

# Estágio 2: Servir a aplicação construída usando Nginx
FROM nginx:alpine

# Copie os arquivos construídos da etapa anterior para o diretório do servidor NGINX
COPY --from=build /app/dist /usr/share/nginx/html

# Exponha a porta que o frontend usará (padrão é 80)
EXPOSE 8080

# O Nginx inicia automaticamente, então não precisa de um comando CMD ou ENTRYPOINT explícito
