# Use uma imagem base de Node.js
FROM node:16.13

# Crie e defina o diretório de trabalho
WORKDIR /app

# Copie os arquivos de dependências
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o código da aplicação
COPY . .

# Exponha a porta que o backend usará
EXPOSE 3000

# Comando para iniciar a aplicação
CMD ["npm", "start"]
